// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notifications.proto

package org.damazio.notifier.protocol;

public final class Notifications {
  private Notifications() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RingNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .org.damazio.notifier.protocol.PhoneNumber number = 1;
    boolean hasNumber();
    org.damazio.notifier.protocol.Common.PhoneNumber getNumber();
  }
  public static final class RingNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements RingNotificationOrBuilder {
    // Use RingNotification.newBuilder() to construct.
    private RingNotification(Builder builder) {
      super(builder);
    }
    private RingNotification(boolean noInit) {}
    
    private static final RingNotification defaultInstance;
    public static RingNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public RingNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .org.damazio.notifier.protocol.PhoneNumber number = 1;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private org.damazio.notifier.protocol.Common.PhoneNumber number_;
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.damazio.notifier.protocol.Common.PhoneNumber getNumber() {
      return number_;
    }
    
    private void initFields() {
      number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, number_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, number_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.RingNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.RingNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.RingNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.RingNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.RingNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.RingNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.RingNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.RingNotification build() {
        org.damazio.notifier.protocol.Notifications.RingNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.RingNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.RingNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.RingNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.RingNotification result = new org.damazio.notifier.protocol.Notifications.RingNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.RingNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.RingNotification.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          mergeNumber(other.getNumber());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNumber()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.damazio.notifier.protocol.Common.PhoneNumber.Builder subBuilder = org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder();
              if (hasNumber()) {
                subBuilder.mergeFrom(getNumber());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNumber(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.damazio.notifier.protocol.PhoneNumber number = 1;
      private org.damazio.notifier.protocol.Common.PhoneNumber number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.damazio.notifier.protocol.Common.PhoneNumber getNumber() {
        return number_;
      }
      public Builder setNumber(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        number_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setNumber(
          org.damazio.notifier.protocol.Common.PhoneNumber.Builder builderForValue) {
        number_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeNumber(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            number_ != org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance()) {
          number_ =
            org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder(number_).mergeFrom(value).buildPartial();
        } else {
          number_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearNumber() {
        number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.RingNotification)
    }
    
    static {
      defaultInstance = new RingNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.RingNotification)
  }
  
  public interface MissedCallNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .org.damazio.notifier.protocol.PhoneNumber number = 1;
    boolean hasNumber();
    org.damazio.notifier.protocol.Common.PhoneNumber getNumber();
    
    // required int32 timestamp = 2;
    boolean hasTimestamp();
    int getTimestamp();
  }
  public static final class MissedCallNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements MissedCallNotificationOrBuilder {
    // Use MissedCallNotification.newBuilder() to construct.
    private MissedCallNotification(Builder builder) {
      super(builder);
    }
    private MissedCallNotification(boolean noInit) {}
    
    private static final MissedCallNotification defaultInstance;
    public static MissedCallNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public MissedCallNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .org.damazio.notifier.protocol.PhoneNumber number = 1;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private org.damazio.notifier.protocol.Common.PhoneNumber number_;
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.damazio.notifier.protocol.Common.PhoneNumber getNumber() {
      return number_;
    }
    
    // required int32 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private int timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTimestamp() {
      return timestamp_;
    }
    
    private void initFields() {
      number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      timestamp_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, number_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, timestamp_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, number_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timestamp_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MissedCallNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.MissedCallNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.MissedCallNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.MissedCallNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.MissedCallNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.MissedCallNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.MissedCallNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.MissedCallNotification build() {
        org.damazio.notifier.protocol.Notifications.MissedCallNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.MissedCallNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.MissedCallNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.MissedCallNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.MissedCallNotification result = new org.damazio.notifier.protocol.Notifications.MissedCallNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.MissedCallNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.MissedCallNotification.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          mergeNumber(other.getNumber());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNumber()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.damazio.notifier.protocol.Common.PhoneNumber.Builder subBuilder = org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder();
              if (hasNumber()) {
                subBuilder.mergeFrom(getNumber());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNumber(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.damazio.notifier.protocol.PhoneNumber number = 1;
      private org.damazio.notifier.protocol.Common.PhoneNumber number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.damazio.notifier.protocol.Common.PhoneNumber getNumber() {
        return number_;
      }
      public Builder setNumber(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        number_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setNumber(
          org.damazio.notifier.protocol.Common.PhoneNumber.Builder builderForValue) {
        number_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeNumber(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            number_ != org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance()) {
          number_ =
            org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder(number_).mergeFrom(value).buildPartial();
        } else {
          number_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearNumber() {
        number_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // required int32 timestamp = 2;
      private int timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.MissedCallNotification)
    }
    
    static {
      defaultInstance = new MissedCallNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.MissedCallNotification)
  }
  
  public interface VoicemailNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required bool has_voicemail = 1 [default = true];
    boolean hasHasVoicemail();
    boolean getHasVoicemail();
  }
  public static final class VoicemailNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements VoicemailNotificationOrBuilder {
    // Use VoicemailNotification.newBuilder() to construct.
    private VoicemailNotification(Builder builder) {
      super(builder);
    }
    private VoicemailNotification(boolean noInit) {}
    
    private static final VoicemailNotification defaultInstance;
    public static VoicemailNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public VoicemailNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required bool has_voicemail = 1 [default = true];
    public static final int HAS_VOICEMAIL_FIELD_NUMBER = 1;
    private boolean hasVoicemail_;
    public boolean hasHasVoicemail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getHasVoicemail() {
      return hasVoicemail_;
    }
    
    private void initFields() {
      hasVoicemail_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHasVoicemail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, hasVoicemail_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hasVoicemail_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.VoicemailNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.VoicemailNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.VoicemailNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.VoicemailNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.VoicemailNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hasVoicemail_ = true;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.VoicemailNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.VoicemailNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.VoicemailNotification build() {
        org.damazio.notifier.protocol.Notifications.VoicemailNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.VoicemailNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.VoicemailNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.VoicemailNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.VoicemailNotification result = new org.damazio.notifier.protocol.Notifications.VoicemailNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hasVoicemail_ = hasVoicemail_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.VoicemailNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.VoicemailNotification.getDefaultInstance()) return this;
        if (other.hasHasVoicemail()) {
          setHasVoicemail(other.getHasVoicemail());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHasVoicemail()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hasVoicemail_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool has_voicemail = 1 [default = true];
      private boolean hasVoicemail_ = true;
      public boolean hasHasVoicemail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getHasVoicemail() {
        return hasVoicemail_;
      }
      public Builder setHasVoicemail(boolean value) {
        bitField0_ |= 0x00000001;
        hasVoicemail_ = value;
        
        return this;
      }
      public Builder clearHasVoicemail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hasVoicemail_ = true;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.VoicemailNotification)
    }
    
    static {
      defaultInstance = new VoicemailNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.VoicemailNotification)
  }
  
  public interface SmsNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .org.damazio.notifier.protocol.PhoneNumber sender = 1;
    boolean hasSender();
    org.damazio.notifier.protocol.Common.PhoneNumber getSender();
    
    // required string text = 2;
    boolean hasText();
    String getText();
  }
  public static final class SmsNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements SmsNotificationOrBuilder {
    // Use SmsNotification.newBuilder() to construct.
    private SmsNotification(Builder builder) {
      super(builder);
    }
    private SmsNotification(boolean noInit) {}
    
    private static final SmsNotification defaultInstance;
    public static SmsNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public SmsNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .org.damazio.notifier.protocol.PhoneNumber sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private org.damazio.notifier.protocol.Common.PhoneNumber sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.damazio.notifier.protocol.Common.PhoneNumber getSender() {
      return sender_;
    }
    
    // required string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getText() {
      Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.SmsNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.SmsNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.SmsNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.SmsNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.SmsNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.SmsNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.SmsNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.SmsNotification build() {
        org.damazio.notifier.protocol.Notifications.SmsNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.SmsNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.SmsNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.SmsNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.SmsNotification result = new org.damazio.notifier.protocol.Notifications.SmsNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.SmsNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.SmsNotification.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.damazio.notifier.protocol.Common.PhoneNumber.Builder subBuilder = org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.damazio.notifier.protocol.PhoneNumber sender = 1;
      private org.damazio.notifier.protocol.Common.PhoneNumber sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.damazio.notifier.protocol.Common.PhoneNumber getSender() {
        return sender_;
      }
      public Builder setSender(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        sender_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          org.damazio.notifier.protocol.Common.PhoneNumber.Builder builderForValue) {
        sender_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            sender_ != org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance()) {
          sender_ =
            org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder(sender_).mergeFrom(value).buildPartial();
        } else {
          sender_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // required string text = 2;
      private Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getText() {
        Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        text_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.SmsNotification)
    }
    
    static {
      defaultInstance = new SmsNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.SmsNotification)
  }
  
  public interface MmsNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .org.damazio.notifier.protocol.PhoneNumber sender = 1;
    boolean hasSender();
    org.damazio.notifier.protocol.Common.PhoneNumber getSender();
    
    // optional string text = 2;
    boolean hasText();
    String getText();
    
    // optional bytes image = 3;
    boolean hasImage();
    com.google.protobuf.ByteString getImage();
  }
  public static final class MmsNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements MmsNotificationOrBuilder {
    // Use MmsNotification.newBuilder() to construct.
    private MmsNotification(Builder builder) {
      super(builder);
    }
    private MmsNotification(boolean noInit) {}
    
    private static final MmsNotification defaultInstance;
    public static MmsNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public MmsNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .org.damazio.notifier.protocol.PhoneNumber sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private org.damazio.notifier.protocol.Common.PhoneNumber sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.damazio.notifier.protocol.Common.PhoneNumber getSender() {
      return sender_;
    }
    
    // optional string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getText() {
      Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes image = 3;
    public static final int IMAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString image_;
    public boolean hasImage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }
    
    private void initFields() {
      sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      text_ = "";
      image_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, image_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, image_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.MmsNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.MmsNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.MmsNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.MmsNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.MmsNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        image_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.MmsNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.MmsNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.MmsNotification build() {
        org.damazio.notifier.protocol.Notifications.MmsNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.MmsNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.MmsNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.MmsNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.MmsNotification result = new org.damazio.notifier.protocol.Notifications.MmsNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.image_ = image_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.MmsNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.MmsNotification.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasImage()) {
          setImage(other.getImage());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.damazio.notifier.protocol.Common.PhoneNumber.Builder subBuilder = org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              image_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.damazio.notifier.protocol.PhoneNumber sender = 1;
      private org.damazio.notifier.protocol.Common.PhoneNumber sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.damazio.notifier.protocol.Common.PhoneNumber getSender() {
        return sender_;
      }
      public Builder setSender(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        sender_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          org.damazio.notifier.protocol.Common.PhoneNumber.Builder builderForValue) {
        sender_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(org.damazio.notifier.protocol.Common.PhoneNumber value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            sender_ != org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance()) {
          sender_ =
            org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder(sender_).mergeFrom(value).buildPartial();
        } else {
          sender_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        sender_ = org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // optional string text = 2;
      private Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getText() {
        Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        text_ = value;
        
      }
      
      // optional bytes image = 3;
      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        image_ = value;
        
        return this;
      }
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        image_ = getDefaultInstance().getImage();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.MmsNotification)
    }
    
    static {
      defaultInstance = new MmsNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.MmsNotification)
  }
  
  public interface BatteryNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional .org.damazio.notifier.protocol.BatteryNotification.State state = 1;
    boolean hasState();
    org.damazio.notifier.protocol.Notifications.BatteryNotification.State getState();
    
    // optional int32 chargePercentage = 2;
    boolean hasChargePercentage();
    int getChargePercentage();
  }
  public static final class BatteryNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements BatteryNotificationOrBuilder {
    // Use BatteryNotification.newBuilder() to construct.
    private BatteryNotification(Builder builder) {
      super(builder);
    }
    private BatteryNotification(boolean noInit) {}
    
    private static final BatteryNotification defaultInstance;
    public static BatteryNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public BatteryNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum State
        implements com.google.protobuf.Internal.EnumLite {
      CHARGING(0, 1),
      DISCHARGING(1, 2),
      NOT_CHARGING(2, 3),
      FULL(3, 4),
      ;
      
      public static final int CHARGING_VALUE = 1;
      public static final int DISCHARGING_VALUE = 2;
      public static final int NOT_CHARGING_VALUE = 3;
      public static final int FULL_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static State valueOf(int value) {
        switch (value) {
          case 1: return CHARGING;
          case 2: return DISCHARGING;
          case 3: return NOT_CHARGING;
          case 4: return FULL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<State>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.valueOf(number);
              }
            };
      
      private final int value;
      
      private State(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:org.damazio.notifier.protocol.BatteryNotification.State)
    }
    
    private int bitField0_;
    // optional .org.damazio.notifier.protocol.BatteryNotification.State state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private org.damazio.notifier.protocol.Notifications.BatteryNotification.State state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.damazio.notifier.protocol.Notifications.BatteryNotification.State getState() {
      return state_;
    }
    
    // optional int32 chargePercentage = 2;
    public static final int CHARGEPERCENTAGE_FIELD_NUMBER = 2;
    private int chargePercentage_;
    public boolean hasChargePercentage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getChargePercentage() {
      return chargePercentage_;
    }
    
    private void initFields() {
      state_ = org.damazio.notifier.protocol.Notifications.BatteryNotification.State.CHARGING;
      chargePercentage_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, chargePercentage_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chargePercentage_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.BatteryNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.BatteryNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.BatteryNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.BatteryNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.BatteryNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        state_ = org.damazio.notifier.protocol.Notifications.BatteryNotification.State.CHARGING;
        bitField0_ = (bitField0_ & ~0x00000001);
        chargePercentage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.BatteryNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.BatteryNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.BatteryNotification build() {
        org.damazio.notifier.protocol.Notifications.BatteryNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.BatteryNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.BatteryNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.BatteryNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.BatteryNotification result = new org.damazio.notifier.protocol.Notifications.BatteryNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chargePercentage_ = chargePercentage_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.BatteryNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.BatteryNotification.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasChargePercentage()) {
          setChargePercentage(other.getChargePercentage());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.damazio.notifier.protocol.Notifications.BatteryNotification.State value = org.damazio.notifier.protocol.Notifications.BatteryNotification.State.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                state_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              chargePercentage_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .org.damazio.notifier.protocol.BatteryNotification.State state = 1;
      private org.damazio.notifier.protocol.Notifications.BatteryNotification.State state_ = org.damazio.notifier.protocol.Notifications.BatteryNotification.State.CHARGING;
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.damazio.notifier.protocol.Notifications.BatteryNotification.State getState() {
        return state_;
      }
      public Builder setState(org.damazio.notifier.protocol.Notifications.BatteryNotification.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value;
        
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = org.damazio.notifier.protocol.Notifications.BatteryNotification.State.CHARGING;
        
        return this;
      }
      
      // optional int32 chargePercentage = 2;
      private int chargePercentage_ ;
      public boolean hasChargePercentage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getChargePercentage() {
        return chargePercentage_;
      }
      public Builder setChargePercentage(int value) {
        bitField0_ |= 0x00000002;
        chargePercentage_ = value;
        
        return this;
      }
      public Builder clearChargePercentage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chargePercentage_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.BatteryNotification)
    }
    
    static {
      defaultInstance = new BatteryNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.BatteryNotification)
  }
  
  public interface ThirdPartyNotificationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string title = 1;
    boolean hasTitle();
    String getTitle();
    
    // optional string description = 2;
    boolean hasDescription();
    String getDescription();
    
    // optional bytes image = 3;
    boolean hasImage();
    com.google.protobuf.ByteString getImage();
  }
  public static final class ThirdPartyNotification extends
      com.google.protobuf.GeneratedMessageLite
      implements ThirdPartyNotificationOrBuilder {
    // Use ThirdPartyNotification.newBuilder() to construct.
    private ThirdPartyNotification(Builder builder) {
      super(builder);
    }
    private ThirdPartyNotification(boolean noInit) {}
    
    private static final ThirdPartyNotification defaultInstance;
    public static ThirdPartyNotification getDefaultInstance() {
      return defaultInstance;
    }
    
    public ThirdPartyNotification getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string title = 1;
    public static final int TITLE_FIELD_NUMBER = 1;
    private Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes image = 3;
    public static final int IMAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString image_;
    public boolean hasImage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }
    
    private void initFields() {
      title_ = "";
      description_ = "";
      image_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, image_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, image_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.damazio.notifier.protocol.Notifications.ThirdPartyNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Notifications.ThirdPartyNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Notifications.ThirdPartyNotification, Builder>
        implements org.damazio.notifier.protocol.Notifications.ThirdPartyNotificationOrBuilder {
      // Construct using org.damazio.notifier.protocol.Notifications.ThirdPartyNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        image_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.damazio.notifier.protocol.Notifications.ThirdPartyNotification getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Notifications.ThirdPartyNotification.getDefaultInstance();
      }
      
      public org.damazio.notifier.protocol.Notifications.ThirdPartyNotification build() {
        org.damazio.notifier.protocol.Notifications.ThirdPartyNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.damazio.notifier.protocol.Notifications.ThirdPartyNotification buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.damazio.notifier.protocol.Notifications.ThirdPartyNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.damazio.notifier.protocol.Notifications.ThirdPartyNotification buildPartial() {
        org.damazio.notifier.protocol.Notifications.ThirdPartyNotification result = new org.damazio.notifier.protocol.Notifications.ThirdPartyNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.image_ = image_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.damazio.notifier.protocol.Notifications.ThirdPartyNotification other) {
        if (other == org.damazio.notifier.protocol.Notifications.ThirdPartyNotification.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasImage()) {
          setImage(other.getImage());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              title_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              description_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              image_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string title = 1;
      private Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        title_ = value;
        
      }
      
      // optional string description = 2;
      private Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        description_ = value;
        
      }
      
      // optional bytes image = 3;
      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        image_ = value;
        
        return this;
      }
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        image_ = getDefaultInstance().getImage();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.ThirdPartyNotification)
    }
    
    static {
      defaultInstance = new ThirdPartyNotification(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.ThirdPartyNotification)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
